s=set()
n=input("Enter no. ")
s.add(int(n))
n=input("Enter no. ")
s.add(int(n))
n=input("Enter no. ")
s.add(int(n))
n=input("Enter no. ")
s.add(int(n))
n=input("Enter no. ")
s.add(int(n))
n=input("Enter no. ")
s.add(int(n))
n=input("Enter no. ")
s.add(int(n))
print(s)